### ISSUE TITLE
Are you planing to release a new Ultimate Developer Tool List?

### ISSUE THREAD

**Issue by jakubsturc** [shanselman/ama#81] opened 2017-08-08 16:00 UTC
Your last [Scott Hanselman's 2014 Ultimate Developer and Power Users Tool List for Windows](https://www.hanselman.com/blog/ScottHanselmans2014UltimateDeveloperAndPowerUsersToolListForWindows.aspx) is from 2014. Do you plan to release the new one? If so, when?

Thanks
Cheers

**Comment by jnm2** [comment] 2017-08-08 18:19
(Duplicate of https://github.com/shanselman/ama/issues/30, https://github.com/shanselman/ama/issues/32, https://github.com/shanselman/ama/issues/39.)

**Comment by shanselman** [comment] 2017-08-08 19:04
Yep, it seems the people have spoken

**Closed as completed by shanselman** 2017-08-08 19:04 UTC
